### ISSUE TITLE
Module loader not working correctly on Windows 10

### ISSUE THREAD

**Issue by IvanDyankov** [VirtuOz/node-dynamic-module-loader#16]
Hi Team,

Just wanted to bring an issue to your attention.

When trying to use the DML on Windows 10, it doesn't quite work. Please review the attached log from our files:
2016-11-16 *** | ERROR | Error: Command failed: find C:\**\**\available-middleware\authentication_1 -name package.json
FIND: Parameter format not correct

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Socket.<anonymous> (internal/child_process.js:330:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:487:12)

We have tried to investigate but with no luck. Can you please assist us with the issue?

Regards,
Ivan

**Comment by sbellone** [comment]
Hello,
Indeed the module is not supported on Windows.
Here we want to check that the file `package.json` is present. We do that by calling the underlying program `find`, which on Linux, is used to search files.
But on Windows, the `find` program is different, it's used to search for a specific string of text in files, see [here](https://technet.microsoft.com/en-us/library/bb490906.aspx). Thus it won't work as expected.

**Comment by sbellone** [comment]
Hi, I've finally taken the time to make it compatible with Windows:  c888d8d
